import type { NextPage } from "next";
import Head from "next/head";
import { Dispatch, SetStateAction, useRef, useState } from "react";
import { Dialog } from "@headlessui/react";

const Drawer = ({
  open,
  setOpen,
}: {
  open: boolean;
  setOpen: Dispatch<SetStateAction<boolean>>;
}) => {
  function close() {
    setOpen(false);
  }

  return (
    <Dialog open={open} onClose={close}>
      <div className="pointer-events-none fixed inset-0 bg-black bg-opacity-25" />
      <div className="fixed inset-0 overflow-y-auto">
        <Dialog.Panel className="h-screen w-60 bg-white">
          <Dialog.Title>Deactivate account</Dialog.Title>
          <Dialog.Description>
            This will permanently deactivate your account
          </Dialog.Description>

          <p>
            Are you sure you want to deactivate your account? All of your data
            will be permanently removed. This action cannot be undone.
          </p>

          <button onClick={close}>Deactivate</button>
          <button onClick={close}>Cancel</button>
        </Dialog.Panel>
      </div>
    </Dialog>
  );
};

const Home: NextPage = () => {
  const [open, setOpen] = useState(false);

  return (
    <>
      <div className="container mx-auto p-8">
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <div className="flex justify-end">
          <button
            type="button"
            onClick={() => setOpen(!open)}
            className="p-4 bg-gray-200"
          >
            TOGGLE MENU
          </button>
        </div>
      </div>

      {open && <Drawer open={open} setOpen={setOpen} />}
    </>
  );
};

export default Home;
